export default [
    "Mario",
    "Black Yoshi",
    "Rosalina",
    "Chef Pee Pee",
    "Bowser Junior",
    "Bowser",
    "Cody",
    "Joseph",
    "Jeffy",
    "Goodman",
    "Shrek",
    "Brooklyn T. Guy",
    "Toad",
    "Ken",
    "Charleyyy",
    "Jackie Chu",
    "Doofy The Dragon",
    "Tyrone Calvin",
    "Craig The Devil",
    "Patrick",
    "Judy",
    "Screwball",
    "Thomas",
    "Sonic",
    "Felipe",
    "Loan Dolphin",
    "Harold Wilfred",
    "Hansel",
    "Chris The Cucumber",
    "Principal Steinbeck",
    "SpongeBob",
    "Mama Luigi",
    "Tony The Tiger",
    "Mr. Pig",
    "Luigi",
    "Woody",
    "Peach",
    "Big Red",
    "Logan Thirtyacre",
    "Lovell Stanton",
    "Lance Thirtyacre",
    "Chris Netherton",
    "Chilly Jimenez",
    "Elaina Keyes",
    "Tito Jimenez",
    "Anthony Miller"
]