export default [
    { Mario: "https://static.wikia.nocookie.net/sml/images/9/92/FullBodyMarioRemastered.png" },
    { "Black Yoshi": "https://static.wikia.nocookie.net/sml/images/4/45/Black_Yoshi.png" },
    { Rosalina: "https://static.wikia.nocookie.net/sml/images/3/35/Rosalina_%28New_-2%29.png" },
    { "Chef Pee Pee": "https://static.wikia.nocookie.net/sml/images/7/7b/Chef_Pee_Pee_New_2.png" },
    { "Bowser Junior": "" },
    { Bowser: "" },
    { Cody: "" },
    { Karen: "https://static.wikia.nocookie.net/sml/images/2/29/Sharon_%28New%29.png" },
    { Cody: "" },
    { Chaz: "https://static.wikia.nocookie.net/sml/images/3/37/Ahhhhhhhh.png" },
    { "Makes Bad Decisions Guy": "https://static.wikia.nocookie.net/sml/images/7/75/MBDG.png" },
    { Joseph: "" },
    { Jeffy: "https://static.wikia.nocookie.net/sml/images/3/35/5FF627B3-ADEB-47ED-BC0E-29908332F74C.webp" },
    { Goodman: "https://static.wikia.nocookie.net/sml/images/c/ce/Mr._Goodman_%28New%29.png" },
    { Shrek: "" },
    { "Brooklyn T. Guy": "https://static.wikia.nocookie.net/sml/images/1/18/BrooklynTGuyRemastered.png" },
    { Toad: "https://static.wikia.nocookie.net/sml/images/a/a5/ToadRemastered.png" },
    { Ken: "" },
    { Charleyyy: "" },
    { "Jackie Chu": "https://static.wikia.nocookie.net/sml/images/9/90/JackieChuNew.png" },
    { "Doofy The Dragon": "" },
    { "Tyrone Calvin": "https://static.wikia.nocookie.net/sml/images/f/f0/Fulltyrone.png" },
    { "Craig The Devil": "" },
    { Patrick: "https://static.wikia.nocookie.net/sml/images/a/a5/Platitudinous_patrick.png" },
    { Judy: "" },
    { Screwball: "https://static.wikia.nocookie.net/sml/images/0/0b/ScrewballSML.PNG" },
    { Thomas: "" },
    { Sonic: "" },
    { Felipe: "https://static.wikia.nocookie.net/sml/images/b/b2/Felipe.png" },
    { "Loan Dolphin": "" },
    { "Harold Wilfred": "https://static.wikia.nocookie.net/sml/images/f/f5/HaroldWilfredRemastered.png" },
    { Hansel: "https://static.wikia.nocookie.net/sml/images/8/8f/SmlHansel.png" },
    { "Chris The Cucumber": "" },
    { "Principal Steinbeck": "" },
    { SpongeBob: "" },
    { "Mama Luigi": "https://static.wikia.nocookie.net/sml/images/3/39/MamaLuigiTransparentOne.png" },
    { "Tony The Tiger": "https://static.wikia.nocookie.net/sml/images/2/2d/TonyTheTigerRemastered.png" },
    { "Mr. Pig": "" },
    { Luigi: "https://static.wikia.nocookie.net/sml/images/7/72/NewSMLLuigi.png" },
    { Woody: "" },
    { Peach: "" },
    { "Big Red": "" },
    { "Logan Thirtyacre": "" },
    { "Lovell Stanton": "" },
    { "Lance Thirtyacre": "" },
    { "Chris Netherton": "https://static.wikia.nocookie.net/sml/images/f/f5/Pooby_rides_a_Byclce_.png" },
    { "Chilly Jimenez": "" },
    { "Elaina Keyes": "" },
    { "Tito Jimenez": "https://static.wikia.nocookie.net/sml/images/2/29/Tito_Jimenez_2019.png" },
    { "Anthony Miller": "https://static.wikia.nocookie.net/sml/images/6/6c/HeyItsAnthony.png" },
];
